TW-1264: Tune analytics events properties structure
madfish-solutions/templewallet-mobile pull request #1028
Opened 2024-01-25 01:27 UTC by alex-tsx

https://madfish.atlassian.net/browse/TW-1264

2024-01-25 09:13 UTC, lourenc requested changes
Please, fix Typescript issues

2024-01-25 09:37 UTC, keshan3262 approved these changes

2024-01-25 09:54 UTC, lendihop approved these changes

2024-01-25 13:34 UTC, lourenc approved these changes

2024-01-26 09:55 UTC, IrynaKhyzhynska approved these changes
done

2024-01-26 11:15 UTC, merged