Add a warning toast for disabled 'Transfer between my accounts' checkbox
madfish-solutions/templewallet-mobile pull request #157
Opened 2021-07-28 08:36 UTC by keshan3262

2021-07-28 08:45 UTC, unixvb commented on src/modals/send-modal/send-modal.tsx
> +                  disabled={ownAccountsReceivers.length === 0}
move ownAccountsReceivers.length === 0 into variable

2021-07-28 08:46 UTC, unixvb approved these changes

2021-07-28 08:47 UTC, andrewkryshtal approved these changes

2021-07-28 10:52 UTC, unixvb requested changes
comment above

2021-07-29 20:38 UTC, unixvb approved these changes

2021-07-29 20:38 UTC, merged