Some-data-doesn't-adapt-on-Android
madfish-solutions/templewallet-mobile pull request #297
Opened 2021-10-29 13:32 UTC by LendiHop

2021-11-01 08:28 UTC, unixvb commented on src/components/activity-groups-list/activity-group-item/activity-group-dollar-amount-change/activity-group-dollar-amount-change.tsx
> +        </Text>
could you reuse `AssetValueText` component instead?

2021-11-01 08:30 UTC, unixvb commented on src/components/activity-groups-list/activity-group-item/activity-group-item.tsx
> +  const nonZeroAmounts = useMemo(() => {
create separate hook with this logic

2021-11-01 08:30 UTC, unixvb commented on src/components/activity-groups-list/activity-group-item/activity-group-item.tsx
> +export interface NonZeroAmounts {
extract interface into seperate file

2021-11-04 10:45 UTC, unixvb commented on src/utils/number.util.ts
> +  return amount.decimalPlaces(amount.abs().lt(1000) ? decimalPlace : 2).toFixed();
add `BigNumber.ROUND_DOWN` ad third argument

2021-11-04 10:48 UTC, unixvb commented on src/utils/big-number.utils.ts
> +const bigIntMin = (...args: BigNumber[]) => args.reduce((m, e) => (e < m ? e : m));
use `BigNumber` `isGreaterThan()` method

2021-11-04 10:49 UTC, unixvb commented on src/components/activity-groups-list/activity-group-item/activity-group-dollar-amount-change/activity-group-dollar-amount-change.tsx
> +          amount={new BigNumber(amount)}
fix `TODO` and remove this BigNumber reation

2021-11-04 15:10 UTC, andrewkryshtal approved these changes

2021-11-04 15:50 UTC, andrewkryshtal approved these changes

2021-11-09 09:29 UTC, unixvb commented on src/utils/number.util.spec.ts
> -
return tests

2021-11-09 09:40 UTC, unixvb requested changes

2021-11-09 09:40 UTC, unixvb commented on src/utils/big-number.utils.ts
> +//Math.max and Math.min analogs
remove this comment

2021-11-09 09:40 UTC, unixvb commented on src/hooks/use-non-zero-amounts.hook.ts
> +        }
remove this ordering

2021-11-09 09:55 UTC, unixvb approved these changes

2021-11-09 10:07 UTC, merged