Parsing-sign-data-for-dApps
madfish-solutions/templewallet-mobile pull request #302
Opened 2021-11-02 15:18 UTC by LendiHop

2021-11-04 09:31 UTC, unixvb commented on src/hooks/parse-sign-payload/parse-sign-payload.ts
> +  };
create `parse-sign-payload.utils.ts` file and move this fn there

2021-11-04 09:34 UTC, unixvb commented on src/hooks/parse-sign-payload/taquito-local-forging.d.ts
> +declare module '@taquito/local-forging/dist/lib/uint8array-consumer';
why this?

2021-11-04 09:34 UTC, unixvb commented on src/hooks/parse-sign-payload/parse-sign-payload.ts
> +    parseSignPayload().then(parsedPayload => setParsedPayload(parsedPayload));
short return

2021-11-04 09:36 UTC, unixvb requested changes

2021-11-04 09:36 UTC, unixvb commented on src/modals/confirmation-modal/d-app-operations-confirmation/sign-payload-request-confirmation/sign-payload-request-confirmation.tsx
> +          />
think about the case when parsing of payload message is going to be unsuccessful

2021-11-04 09:47 UTC, LendiHop commented on src/hooks/parse-sign-payload/taquito-local-forging.d.ts
> +declare module '@taquito/local-forging/dist/lib/uint8array-consumer';
imports don't work without it

2021-11-05 09:20 UTC, andrewkryshtal approved these changes

2021-11-08 08:39 UTC, unixvb commented on src/utils/taquito-local-forging.utils.d.ts
> +declare module '@taquito/local-forging/dist/lib/michelson/codec';
rename this file to `parse-sign-payload.utils.d.ts` please

2021-11-08 08:41 UTC, unixvb commented on src/modals/confirmation-modal/d-app-operations-confirmation/sign-payload-request-confirmation/sign-payload-request-confirmation.tsx
> +  const isPayloadParsed = isString(payloadPreview);
move this flag into `useParseSignPayloadHook`

2021-11-08 10:28 UTC, unixvb approved these changes

2021-11-08 10:53 UTC, merged