TW-485: Sort tokens by dollar value
madfish-solutions/templewallet-mobile pull request #764
Opened 2023-03-06 15:00 UTC by alex-tsx

2023-03-06 16:06 UTC, keshan3262 requested changes

2023-03-07 12:36 UTC, keshan3262 submitted a review, later dismissed

2023-03-07 13:31 UTC, herkoss approved these changes
Well done!)

2023-03-08 13:09 UTC, keshan3262 approved these changes

2023-03-09 14:49 UTC, herkoss approved these changes
GJ!

2023-03-09 14:49 UTC, herkoss commented on src/hooks/use-filtered-assets-list.hook.ts
> +      if (filterZeroBalances && !isNonZeroBalance(leadingAsset)) {
Maybe we need `isZeroBalance` helper?

2023-03-09 15:45 UTC, keshan3262 approved these changes

2023-03-10 13:31 UTC, IrynaKhyzhynska approved these changes
build version: 1.14_565б android done

2023-03-10 13:38 UTC, NovakVlad2424 approved these changes
build version: 1.14_565 ios done

2023-03-13 09:07 UTC, merged