Tw 368 Add APR label to Youves tokens
madfish-solutions/templewallet-mobile pull request #767
Opened 2023-03-17 15:19 UTC by svjatoslavtt

2023-03-22 12:00 UTC, herkoss reviewed
Well done!
Let's improve this solution!)

2023-03-22 12:00 UTC, herkoss commented on src/utils/get-delegate-text.util.ts
> +  (youvesTokens as string[]).includes(token.symbol) ? 'APR' : 'APY';
Remove this assertion, please

2023-03-27 07:52 UTC, unixvb submitted a review, later dismissed

2023-03-28 08:11 UTC, herkoss reviewed
Well done!

2023-03-28 08:11 UTC, herkoss commented on src/apis/youves/index.ts
> +      console.log('Youves error: get YOU token APR', error);
Delete this `console.log`

2023-03-28 08:11 UTC, herkoss commented on src/apis/youves/index.ts
> +      return of(0);
Fix magic numbers. `DEFAULT_APR` for example

2023-03-28 08:33 UTC, svjatoslavtt commented on src/apis/youves/index.ts
> +      console.log('Youves error: get YOU token APR', error);
why?

2023-03-28 10:41 UTC, herkoss submitted a review, later dismissed

2023-06-20 06:19 UTC, herkoss reviewed
GJ!

2023-06-20 06:19 UTC, herkoss commented on package.json
> +    "bignumber.js": "9.1.1"
Why do we need these dev deps?

2023-06-20 06:19 UTC, herkoss commented on src/components/token-screen-content-container/token-header.tsx
> +const DECIMAL_VALUE = 2;
The same in `DelegateTag`. Move to constants, please

2023-06-20 07:59 UTC, svjatoslavtt commented on package.json
> +    "bignumber.js": "9.1.1"
because we have conflicts of version

2023-06-20 09:01 UTC, herkoss submitted a review, later dismissed

2023-06-20 09:10 UTC, Boltman92 approved these changes

2023-06-21 11:12 UTC, herkoss approved these changes

2023-06-21 11:13 UTC, Boltman92 submitted a review, later dismissed

2023-06-22 08:00 UTC, NovakVlad2424 submitted a review, later dismissed
done ios, android: 1.15_751

2023-06-22 10:58 UTC, lourenc requested changes

2023-06-22 10:58 UTC, lourenc commented on babel.config.js
> +  plugins: ['react-native-reanimated/plugin', ['@babel/plugin-proposal-decorators', { legacy: true }]],
It's an unnecessary change

2023-06-22 10:58 UTC, lourenc commented on package.json
> +    "@babel/plugin-proposal-decorators": "^7.21.0",
Please, remove the decorators support. It's not needed at all.

2023-06-22 11:32 UTC, merged