Tw 673 sort by deposited only
madfish-solutions/templewallet-mobile pull request #821
Opened 2023-05-19 15:11 UTC by herkoss

2023-05-23 10:17 UTC, keshan3262 approved these changes

2023-06-20 07:56 UTC, keshan3262 commented on src/hooks/use-filtered-farms.hook.ts
> +        result.reverse();
If liquidity baking "farm", which is the oldest, should be at the bottom by default, then this sorting won't work correctly and we should make up another way to sort farms. Moreover, Youves farms may add some more headaches here. Consider fetching contracts origination date from TZKT

2023-06-20 07:56 UTC, keshan3262 commented on src/screens/earn/farm-item/farm-item.styles.ts
> +export const useFarmItemStyles = createUseStyles(({ colors, typography }) => ({
Does `createUseStylesMemoized` cause any trouble here?

2023-06-20 13:13 UTC, keshan3262 approved these changes

2023-06-22 13:43 UTC, keshan3262 commented on src/utils/earn.utils.ts
> +  new Date(farmB?.item?.firstActivityTime ?? Date.now()).getTime();
```suggestion
export const sortByOldest = (farmA: SingleFarmResponse, farmB: SingleFarmResponse) => -sortByNewest(farmA, farmB);
```
Please check for prettier errors before committing this suggestion

2023-06-22 15:36 UTC, keshan3262 requested changes

2023-06-22 15:36 UTC, keshan3262 commented on src/utils/earn.utils.ts
> +export const sortByOldest = (farmA: SingleFarmResponse, farmB: SingleFarmResponse) => sortByNewest(farmB, farmA);
```suggestion
export const sortByOldest = (farmA: SingleFarmResponse, farmB: SingleFarmResponse) => -sortByNewest(farmB, farmA);
```

2023-06-22 15:37 UTC, keshan3262 approved these changes

2023-06-26 07:53 UTC, keshan3262 approved these changes

2023-06-29 07:55 UTC, keshan3262 commented on src/hooks/use-filtered-farms.hook.ts
> +            { name: token?.metadata?.name, symbol: token?.metadata?.symbol, address: token?.contractAddress },
The same

2023-06-29 15:55 UTC, keshan3262 approved these changes

2023-06-30 10:51 UTC, IrynaKhyzhynska approved these changes
build number: 1.15_768 android done

2023-06-30 10:51 UTC, vladvn1905 approved these changes
ios done build: 1.15_768

2023-07-04 08:07 UTC, merged