TW-916 Upload APK to Digital Ocean Spaces + build identifier event
madfish-solutions/templewallet-mobile pull request #902
Opened 2023-08-02 15:39 UTC by lendihop

2023-08-02 17:29 UTC, keshan3262 approved these changes

2023-08-14 12:50 UTC, lourenc requested changes

2023-08-14 13:25 UTC, lourenc submitted a review, later dismissed

2023-08-16 11:46 UTC, lendihop commented on src/screens/wallet/wallet.tsx
> +  useBuildIdentifierEvent();
the problem is that 'APK_BUILD_LAUNCH' event wont fire at root-stack, cause user didnt enabled analytics yet. The same problem was with 'PUSH_NOTIFICATIONS_ENABLED' event, thats why i made a little refactor.

2023-08-17 09:15 UTC, lourenc approved these changes

2023-08-17 10:10 UTC, merged