TW-726: In-App Browser. For dApps
madfish-solutions/templewallet-mobile pull request #907
Opened 2023-08-08 17:51 UTC by alex-tsx

https://madfish.atlassian.net/browse/TW-726

2023-08-09 07:35 UTC, keshan3262 reviewed
Introducing `TruncatedText` component looks like a topic for a separate PR but let it be like this

2023-08-09 07:35 UTC, keshan3262 commented on ios/Podfile.lock
> -COCOAPODS: 1.12.1
Sorry, is this version rollback necessary?

2023-08-09 07:35 UTC, keshan3262 commented on src/components/truncated-text.tsx
> +  <Text numberOfLines={1} ellipsizeMode="tail" {...props} style={[props.style, { flexShrink: 1 }]} />
Please consider extracting some values from `props` and using the rest props to avoid spreading props in the middle

2023-08-10 10:47 UTC, Boltman92 commented on src/screens/market/tezos-info/tezos-info.tsx
> +            <TruncatedText style={{ ...styles.subtitle11, color: priceChange24hColor }}>{priceChange24h}</TruncatedText>
I'm not sure that is the difference, but usually we pass styles like this:
`style={[styles.subtitle11, { color: priceChange24hColor }]}`

2023-08-10 10:48 UTC, Boltman92 submitted a review, later dismissed

2023-08-10 12:33 UTC, lourenc requested changes

2023-08-10 12:33 UTC, lourenc commented on src/modals/in-app-browser/index.tsx
> +  // PRT (pull-to-refresh)
The comment states an invalid abbreviation, it has to be PTR :)

2023-08-10 12:33 UTC, lourenc commented on src/utils/network.utils.ts
> +export const isDcpNode = mem((selectedRpcUrl: string) => new URL(selectedRpcUrl).href === DCP_NODE_RPC_URL);
I don't think we need memoization here - we usually use it for computation-heavy functions, but this one is pretty simple. Memoization in such cases even may add more performance overhead.

2023-08-10 13:40 UTC, keshan3262 approved these changes

2023-08-10 14:19 UTC, Boltman92 submitted a review, later dismissed

2023-08-28 14:31 UTC, keshan3262 approved these changes

2023-08-28 15:15 UTC, lourenc submitted a review, later dismissed

2023-08-28 18:03 UTC, Boltman92 approved these changes

2023-09-04 08:59 UTC, keshan3262 approved these changes

2023-09-04 09:39 UTC, Boltman92 approved these changes

2023-09-04 14:31 UTC, NovakVlad2424 approved these changes
ios done

2023-09-04 15:26 UTC, lourenc approved these changes

2023-09-04 15:26 UTC, merged