TW-1039: Add Earn button to Dapps page
madfish-solutions/templewallet-mobile pull request #933
Opened 2023-08-28 16:38 UTC by lendihop

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1039

2023-08-28 16:45 UTC, keshan3262 requested changes

2023-08-29 10:43 UTC, herkoss approved these changes

2023-08-29 11:51 UTC, keshan3262 approved these changes

2023-08-30 09:56 UTC, NovakVlad2424 approved these changes
ios android: done 1.15_906

2023-08-30 12:54 UTC, merged